const router = require("express").Router();
const auth_controller = require("../controllers/auth_controller");
const validator = require("../middlewares/validation_middleware");
router.get("/login", auth_controller.loginFormunuGoster);
router.post("/login", validator.validateLogin(), auth_controller.login);
router.get("/register", auth_controller.registerFormunuGoster);
router.post("/register", validator.validateNewUser(), auth_controller.register);
router.get("/forgot-password", auth_controller.forgotPasswordFormunuGoster);
router.post("/forgot-password", auth_controller.forgotPassword);
module.exports = router;
